# Generated by Django 2.1.3 on 2018-11-28 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('file_type', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('encryption_scheme', models.CharField(max_length=100)),
                ('md5code', models.TextField()),
                ('file_path', models.TextField()),
                ('last_update_by', models.CharField(max_length=5000)),
                ('file_contents', models.TextField()),
                ('owners', models.ManyToManyField(related_name='dirfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
