# Generated by Django 2.1.3 on 2018-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('file_type', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('encryption_scheme', models.CharField(max_length=100)),
                ('md5code', models.TextField()),
                ('file_path', models.TextField()),
                ('file_contents', models.TextField()),
            ],
        ),
    ]
