# Generated by Django 2.1.3 on 2018-12-26 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181201_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirfile',
            name='lock_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dirfile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
